export const refs = {
  scrollToTopBtn: document.querySelector('.scrollToTopBtn'),
  main: document.querySelector('.main'),
  footer: document.querySelector('.footer'),
  themeCheckbox: document.querySelector('.theme-checkbox'),
  headerLogo: document.querySelector('.logo'),
  navList: document.querySelector('.navList'),
  headerWrapper: document.querySelector('.headerWrapper'),
  header: document.querySelector('.header'),
  authTitle: document.querySelector('.auth-modal__title'),
  authForm: document.forms.auth,
  authSbmBtn: document.querySelector('.auth-modal__submit-btn'),
  authBackdrop: document.querySelector('.auth-backdrop'),
  authModalClose: document.querySelector('.auth-modal__close'),
  trendingMovies: document.querySelector('.trending-movies-list'),
  filmModal: {
    filmModalBackdrop: document.querySelector('.film-backdrop'),
    filmModalCloseButton: document.querySelector('.modal__button-in'),
    filmModalImage: document.querySelector('.cinema__image'),
    filmModalTitle: document.querySelector('.info-data1'),
    filmModalVote: document.querySelector('.info-data2-acent1'),
    filmModalVotes: document.querySelector('.info-data2-acent2'),
    filmModalPopularity: document.querySelector('.info-data3'),
    filmModalOriginalTitle: document.querySelector('.info-data4'),
    filmModalGenre: document.querySelector('.info-data5'),
    filmModalAbout: document.querySelector('.info-data6'),
    filmModalButtons: document.querySelector('.modal__button-add'),
    addToWatched: document.querySelector('.add-to-watched'),
    addToQueue: document.querySelector('.add-to-queue'),
    delete: document.querySelector('.delete'),
  },
  modalStudents: {
    openButton: document.querySelector('.footer__button'),
    closeButton: document.querySelector('.closeStudentsModal'),
    backdrop: document.querySelector('.js-backdropStudents'),
  },
  paginationList: document.querySelector('.pagination-list'),
};
